name: test actions
on:
  tags:
    - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: show GITHUB_REF
        run: |
          echo $GITHUB_REF
          echo ${GITHUB_REF:10}
          echo ${GITHUB_REF:11}
          
      - name: show github ref
        run: echo $github.ref
        
      - name: when dev
        run: echo publish dev
        if: endsWith(GITHUB_REF,'dev')
        
      - name: when prod
        run: echo publish prod
        if: endsWith(GITHUB_REF,'prod')