name: test actions
on:
  push:
    tags:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: show GITHUB_REF
        run: |
          echo $GITHUB_REF
          echo ${GITHUB_REF:10}
          echo ${GITHUB_REF:11}
          
      - name: show github ref
        run: echo ${{github.ref}}
          
      - name: show nupkg file
        run: ls ${GITHUB_REF:11}.nupkg
        
      - name: when dev
        if: !endsWith(github.ref,'dev')
        run: echo publish dev
        
      - name: when prod
        if: endsWith(github.ref,'prod')
        run: echo publish prod